// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Companies = sequelize.define('companies', {
    description: {
      type: DataTypes.STRING,
    },
    industry: {
      type: DataTypes.STRING,
    },
    headquarters: {
      type: DataTypes.STRING,
    },
    name: {
      type: DataTypes.STRING,
    },
    status: {
      type: DataTypes.STRING,
    },
    createdAt: {
      type: DataTypes.DATEONLY,
      defaultValue: Sequelize.literal('now()'),
    },
    crmId: {
      type: DataTypes.BIGINT,
    },
    pipedriveId: {
      type: DataTypes.BIGINT,
    },
  }, {
    tableName: 'companies',
    underscored: true,
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Companies.associate = (models) => {
    Companies.hasMany(models.subscriptions, {
      foreignKey: {
        name: 'companyIdKey',
        field: 'company_id',
      },
      as: 'subscriptions',
    });
    Companies.hasMany(models.users, {
      foreignKey: {
        name: 'companyIdKey',
        field: 'company_id',
      },
      as: 'users',
    });
  };

  return Companies;
};
