// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Subscriptions = sequelize.define('subscriptions', {
    price: {
      type: DataTypes.INTEGER,
    },
    periodicity: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'subscriptions',
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Subscriptions.associate = (models) => {
    Subscriptions.belongsTo(models.planCategories, {
      foreignKey: {
        name: 'planCategoryIdKey',
        field: 'plan_category_id',
      },
      as: 'planCategory',
    });
    Subscriptions.belongsTo(models.companies, {
      foreignKey: {
        name: 'companyIdKey',
        field: 'company_id',
      },
      as: 'company',
    });
    Subscriptions.hasMany(models.subscriptionFeatures, {
      foreignKey: {
        name: 'subscriptionIdKey',
        field: 'subscription_id',
      },
      as: 'subscriptionFeatures',
    });
  };

  return Subscriptions;
};
